### ISSUE TITLE
Can't launch lookit on Arch Linux

### ISSUE THREAD

**Issue by dcelasun** [zachtib/lookit#15]
Hi,

I'm the maintainer of "indicator-lookit" on Arch Linux. See the package here: http://aur.archlinux.org/packages.php?ID=46500

The package builds lookit with the following:

<pre>python2 setup.py build
python2 setup.py install --prefix=/usr</pre>

It builds and installs fine, but when I try to invoke it, I get this:

<pre>
$ lookit
SFTP support not found
Ubuntu One support not found
Imgur support not available
Unable to load prefs
Traceback (most recent call last):
  File "/usr/bin/lookit", line 248, in <module>
    app = LookitApp()
  File "/usr/bin/lookit", line 68, in __init__
    stdout=subprocess.PIPE).communicate()[0] \
  File "/usr/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1202, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

**Comment by dcelasun** [comment]
Upon further examining the code, I realized lookit depends on "xdg-user-dirs" package. Everything works fine now.
