### ISSUE TITLE
Preferences menu is inaccessible

### ISSUE THREAD

**Issue by Rogach** [zachtib/lookit#56]
I'm using Linux Mate 13 (Maya), with Mate desktop. If I try to select `Preferences` option from the lookit menu, nothing happens, and the following is printed to console:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/lookit/lookitindicator.py", line 129, in handle_menu_item
    liblookit.do_preferences()
  File "/usr/lib/pymodules/python2.7/lookit/liblookit.py", line 81, in do_preferences
    preferences.PreferencesDialog().run()
  File "/usr/lib/pymodules/python2.7/lookit/preferences.py", line 63, in run
    value = self.config.get(section, option)
  File "/usr/lib/pymodules/python2.7/lookit/lookitconfig.py", line 58, in get
    password = keyring.get_password('lookit', 'lookit')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
    _, session = service_iface.OpenSession("plain", "")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist
```

**Comment by Rogach** [comment]
I'm using lookit 1.2.0, installed from daily PPA.
